#!/usr/bin/env bash
# MIT License
#
# Installs the fine-tune toolchain on Ubuntu, ONCE. This is the single home for these
# installs: a human follows the README and runs it; the Azure runner
# (nl-assist-finetune/infra/bootstrap.sh) runs this exact script - neither re-implements it.
#
# Installs: build tools (build-essential, cmake), git/curl/jq, Node.js 22 + tsx, .NET SDK 10
# (the apiApp compile authority), uv + Python 3.13 (PyTorch has no CUDA wheels for 3.14), and
# Ollama. Idempotent; works as root (the VM) or via sudo (a human). It does NOT start Ollama
# and does NOT install the NVIDIA driver - see the README.
#
# After it runs, source the env file it writes to pick up DOTNET_ROOT / PATH / PY313:
#     ./install-prereqs.sh && source ./.prereqs-env.sh
#     PYTHON="$PY313" ./run.sh all
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENVFILE="$HERE/.prereqs-env.sh"
DOTNET_DIR=/usr/local/dotnet
SUDO=""; [ "$(id -u)" -ne 0 ] && SUDO="sudo"
# Wait up to 10 min for the apt/dpkg lock - on an Azure GPU VM the NVIDIA driver extension
# installs concurrently and holds it; without this apt fails with "Could not get lock".
APT="$SUDO apt-get -o DPkg::Lock::Timeout=600"
export DEBIAN_FRONTEND=noninteractive
CURL="curl -fsSL --connect-timeout 30 --max-time 900 --retry 3"
log(){ echo "[install-prereqs] $*"; }

log "apt: build tools, git, curl, jq..."
$APT update -y
$APT install -y build-essential cmake git curl jq ca-certificates

if ! command -v node >/dev/null 2>&1; then
  log "Node.js 22 (NodeSource)..."
  $CURL https://deb.nodesource.com/setup_22.x | $SUDO bash -
  $APT install -y nodejs
fi
log "tsx (so run.sh's npx never prompts)..."
$SUDO npm install -g tsx || log "WARN: tsx global install failed; run.sh's npx will fetch it on demand (callers set npm_config_yes)"

if [ ! -x "$DOTNET_DIR/dotnet" ]; then
  log ".NET SDK 10 -> $DOTNET_DIR ..."
  $CURL https://dot.net/v1/dotnet-install.sh -o /tmp/dotnet-install.sh
  $SUDO bash /tmp/dotnet-install.sh --channel 10.0 --install-dir "$DOTNET_DIR"
fi

if ! command -v uv >/dev/null 2>&1; then
  log "uv..."
  $CURL https://astral.sh/uv/install.sh | sh
fi
export PATH="$HOME/.local/bin:$PATH"
# shellcheck disable=SC1091
. "$HOME/.local/bin/env" 2>/dev/null || true
log "Python 3.13 via uv (CUDA torch wheels don't exist for 3.14)..."
uv python install 3.13
PY313="$(uv python find 3.13)"

if ! command -v ollama >/dev/null 2>&1; then
  log "Ollama..."
  # The installer runs `modprobe nvidia`; before the GPU driver extension has loaded the module
  # that prints "could not insert 'nvidia': No such device" and can make the script exit non-zero.
  # Harmless here - Ollama only needs CPU to create/push, and bootstrap waits for the GPU later -
  # so tolerate a non-zero exit, then verify the binary actually installed.
  $CURL https://ollama.com/install.sh | sh || log "WARN: ollama install exited non-zero (likely the GPU modprobe warning) - verifying the binary..."
  command -v ollama >/dev/null 2>&1 || { echo "[install-prereqs] ERROR: ollama not on PATH after the install script." >&2; exit 1; }
fi

cat > "$ENVFILE" <<EOF
# Generated by install-prereqs.sh - source this to use the installed toolchain.
export DOTNET_ROOT="$DOTNET_DIR"
export PATH="$DOTNET_DIR:$HOME/.local/bin:\$PATH"
export PY313="$PY313"
EOF

log "done. Toolchain installed."
log "next:  source $ENVFILE  then  PYTHON=\$PY313 ./run.sh all"
