#!/usr/bin/env bash
# End-to-end fine-tune pipeline (nl-assist-finetune plan phase 3, spec Stages 1-6, FT-1).
# Runs on WSL2 (Ubuntu) with an 8GB+ NVIDIA GPU. Each stage is a function and can be run
# alone:  ./run.sh <stage>   where stage is one of
#   deps | dataset | train | merge | gguf | modelfile | provenance | all   (default: all)
#
# Prerequisites the pipeline does NOT install for you:
#   - Python 3.10+ and a CUDA 12.x driver visible in WSL2 (`nvidia-smi` works)
#   - Node.js + npx           (for the phase-2 dataset generator)
#   - ollama                  (for `ollama create`; Windows or WSL install both work)
#   - a reachable Fallen-8 apiApp with EnableDynamicCodeExecution=true, for dataset
#     validation - set NL_EVAL_F8 if it isn't http://localhost:5000
#
# Env overrides: VENV, LLAMA_CPP (existing llama.cpp checkout), NL_EVAL_F8, OLLAMA_MODEL.
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO="$(cd "$HERE/.." && pwd)"
VENV="${VENV:-$HERE/train/.venv}"
DATASET="$HERE/dataset/train.jsonl"
ADAPTER="$HERE/adapter"
MERGED="$HERE/merged"
CONFIG="$HERE/train/train-config.json"
LLAMA_CPP="${LLAMA_CPP:-$HERE/llama.cpp}"
OLLAMA_MODEL="${OLLAMA_MODEL:-$(python3 -c "import json;print(json.load(open('$CONFIG'))['output']['ollamaModel'])")}"
GGUF_QUANT="$(python3 -c "import json;print(json.load(open('$CONFIG'))['output']['ggufQuant'])")"
GGUF_F16="$HERE/${OLLAMA_MODEL}.f16.gguf"
GGUF_QUANTIZED="$HERE/${OLLAMA_MODEL}.${GGUF_QUANT}.gguf"

log() { printf '\n\033[1;36m== %s ==\033[0m\n' "$*"; }
py() { "$VENV/bin/python" "$@"; }

deps() {
  log "deps: python venv + pinned toolchain"
  [ -d "$VENV" ] || python3 -m venv "$VENV"
  "$VENV/bin/pip" install --upgrade pip >/dev/null
  "$VENV/bin/pip" install -r "$HERE/train/requirements.txt"
}

dataset() {
  log "dataset (phase 2): generate/validate (needs apiApp at ${NL_EVAL_F8:-http://localhost:5000})"
  if [ -f "$DATASET" ]; then
    # Present already: only confirm it still matches the delegate contract (spec FT-2).
    (cd "$REPO" && npx tsx nl-assist-finetune/dataset-gen/generate.ts --check)
  else
    (cd "$REPO" && npx tsx nl-assist-finetune/dataset-gen/generate.ts)
  fi
}

train()   { log "train (Stage 2): QLoRA -> $ADAPTER"; py "$HERE/train/train_lora.py" --dataset "$DATASET" --out "$ADAPTER"; }
merge()   { log "merge (Stage 3): adapter -> merged fp16"; py "$HERE/train/merge.py" --adapter "$ADAPTER" --out "$MERGED"; }

gguf() {
  log "gguf (Stage 4): convert + quantize to $GGUF_QUANT"
  if [ ! -d "$LLAMA_CPP" ]; then
    git clone --depth 1 https://github.com/ggml-org/llama.cpp "$LLAMA_CPP"
  fi
  "$VENV/bin/pip" install -r "$LLAMA_CPP/requirements.txt" >/dev/null
  if [ ! -x "$LLAMA_CPP/build/bin/llama-quantize" ]; then
    cmake -S "$LLAMA_CPP" -B "$LLAMA_CPP/build" -DGGML_CUDA=ON
    cmake --build "$LLAMA_CPP/build" --config Release -j --target llama-quantize
  fi
  py "$LLAMA_CPP/convert_hf_to_gguf.py" "$MERGED" --outfile "$GGUF_F16" --outtype f16
  "$LLAMA_CPP/build/bin/llama-quantize" "$GGUF_F16" "$GGUF_QUANTIZED" "$GGUF_QUANT"
}

modelfile() {
  log "modelfile (Stage 5-6): write Modelfile + ollama create $OLLAMA_MODEL"
  sed "s#__GGUF__#$GGUF_QUANTIZED#" "$HERE/train/Modelfile.template" > "$HERE/Modelfile"
  ollama create "$OLLAMA_MODEL" -f "$HERE/Modelfile"
  echo "registered '$OLLAMA_MODEL' - point the NL assist's model field at it (spec FT-6)."
}

provenance() {
  log "provenance (FT-7): PROVENANCE.md"
  local base license versions srchash rows
  base="$(python3 -c "import json;print(json.load(open('$CONFIG'))['baseModel'])")"
  license="$(python3 -c "import json;print(json.load(open('$CONFIG'))['baseModelLicense'])")"
  versions="$("$VENV/bin/pip" freeze | grep -iE '^(torch|transformers|peft|trl|datasets|accelerate|bitsandbytes)==' || true)"
  srchash="$(python3 -c "import json;print(json.load(open('$HERE/dataset/dataset.meta.json'))['sourceHash'])" 2>/dev/null || echo '(dataset not generated)')"
  rows="$(python3 -c "import json;print(json.load(open('$HERE/dataset/dataset.meta.json'))['generatedRows'])" 2>/dev/null || echo '?')"
  cat > "$HERE/PROVENANCE.md" <<EOF
# f8-delegate provenance

Generated by run.sh. The produced adapter/GGUF is the operator's artifact on the operator's
machine; Fallen-8 ships neither weights nor a trainer (spec FT-5).

## Base model
- \`$base\` - license: **$license** (MIT-only pipeline, spec FT-7 / parent FR-26.1).

## Dataset
- Grounded in the repo's delegate contract; sourceHash \`$srchash\`, $rows validated rows.
- Every row compiled via POST /delegates/validate at generation time (spec FT-2).

## Tooling (pinned, this run)
\`\`\`
$versions
\`\`\`
- llama.cpp (GGUF convert + quantize): $LLAMA_CPP
- Quantization: $GGUF_QUANT

## Reproduce
\`\`\`
./run.sh all
\`\`\`
Same dataset + train-config.json + seed => equivalent model (spec FT-1).
EOF
  echo "wrote $HERE/PROVENANCE.md"
}

all() { deps; dataset; train; merge; gguf; modelfile; provenance; log "done. Next: evaluate (phase 4) with NL_EVAL_MODEL=$OLLAMA_MODEL"; }

"${1:-all}"
