// MIT License
//
// IPathTraverser.cs
//
// Copyright (c) 2025 Henning Rauch
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
//
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

namespace NoSQL.GraphDB.Core.Algorithms.Path
{
    /// <summary>
    ///   The delegate factory a compiled path filter/cost set implements. Each method receives
    ///   the request's <see cref="TraversalContext" /> (feature element-embeddings) and returns
    ///   the delegate for this traversal - a fragment may close over <c>context</c> (e.g.
    ///   <c>context.TrySimilarity(v, out var s)</c>) or ignore it; a <c>null</c> delegate means
    ///   match-everything / default cost. Implementations are generated by
    ///   <c>CodeGenerationHelper</c> and cached process-wide keyed on their fragments, so the
    ///   per-request state lives in the context parameter, never on the instance.
    /// </summary>
    public interface IPathTraverser
    {
        Delegates.EdgePropertyFilter EdgePropertyFilter(TraversalContext context);
        Delegates.VertexFilter VertexFilter(TraversalContext context);
        Delegates.EdgeFilter EdgeFilter(TraversalContext context);
        Delegates.EdgeCost EdgeCost(TraversalContext context);
        Delegates.VertexCost VertexCost(TraversalContext context);
    }
}
